const categories = [ {name: "Apparels", products: [
    {title: "Mobaco Cotton Oversized Printed T-Shirt - Red", description: "Soft and smooth jersey fabrication, providing added comfort, Ribbed collar, Lightweight and breathable, Highly durable fabric, Great drapability 100% Cotton", price: "290", img: "https://mobaco.com/wp-content/uploads/2024/05/ST385_0170_FIT1.jpg"},
    {title: "Cottonil Men's Derby Tank top - Black", description: "100% Egyptian Cotton Super Soft men's underwear Keeps You Comfortable And Refreshed All Day", price: "100", img: "https://www.cottonilonline.com/cdn/shop/files/S22DRTT01-Navy_5_2.jpg?v=1684594219&width=600"},
    {title: "Mobaco Round Neck Cotton Printed T-Shirt - Black", description: "Soft and smooth jersey fabrication, providing added comfort, Ribbed collar, Lightweight and breathable, Highly durable fabric, Great drapability 100% Cotton", price: "240", img: "https://mobaco.com/wp-content/uploads/2024/04/ST396_0020_1.jpg"},
    {title: "Cottonil Men's Derby Tank top - White", description: "100% Egyptian Cotton Super Soft men's underwear Keeps You Comfortable And Refreshed All Day", price: "100", img: "https://www.cottonilonline.com/cdn/shop/files/S22DRTT01-White_1.jpg?v=1684594929&width=1946"},
    {title: "Cottonil Men's CUT Derby (O) Neck - Baby Blue", description: "100% Egyptian Cotton Super Soft men's underwear Keeps You Comfortable And Refreshed All Day", price: "200", img: "https://www.cottonilonline.com/cdn/shop/files/3118.jpg?v=1685288599&width=600"}
]}, {name: "Electronics", products: [
    {title: "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ", description: "49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag", price: "46649", img: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg"},
    {title: "Samsung Galaxy Z Fold 5 - Ice Blue", description: "", price: "64,999", img: "https://images.samsung.com/eg/smartphones/galaxy-z-fold5/buy/kv_hero_PC.jpg?imbypass=true"},
    {title: "Samsung Galaxy A24 - Silver", description: "", price: "7899", img: "https://images.samsung.com/is/image/samsung/p6pim/eg/sm-a245fzsumea/gallery/eg-galaxy-a24-sm-a245-sm-a245fzsumea-536259448?$650_519_PNG$"},
    {title: "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin", description: "21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz", price: "27927", img: "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg"},
    {title: "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s", description: "Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)", price: "5081", img: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg"},
    {title: "Samsung 50 Inch 4K UHD Smart LED TV with Built-in Receiver and Remote Control - Black - UA50CU7000UXEG [2023 Model]", description: "", price: "16799", img: "https://m.media-amazon.com/images/I/61ckfbfWrfL._AC_SX522_.jpg"}
]}, {name: "Appliances", products: [
    {title: "Samsung Ecobubble™ Front Load Washing Machine with SmartThings AI Power Mode - Black", description: "", price: "31999", img: "https://images.samsung.com/is/image/samsung/p6pim/eg/ww90cgc0edabas/gallery/eg-ww5000c-ww90cgc0edabas-539287039?$650_519_PNG$"},
    {title: "Samsung Canister Vacuum Cleaner, VC18M31A0HP Bagless, 1,800W", description: "", price: "6199", img: "https://images.samsung.com/is/image/samsung/eg-canister-sc18m31a0hp-vc18m31a0hp-gt-frontpink-82670111?$650_519_PNG$"},
    {title: "Samsung RB7300 Bottom Freezer Refrigerator with BESPOKE - Height 1853", description:"", price:"44999", img: "https://images.samsung.com/is/image/samsung/p6pim/eg/rb34a6b0e41-mr/gallery/eg-bespoke-rb7300t-rb34a6b0e41-mr-534504517?$650_519_PNG$"}
]} ]

export {categories}